add features/updated yml/fix typos

diff --git a/01_scripts/04_jellyfish b/01_scripts/04_jellyfish
--- a/01_scripts/04_jellyfish
+++ b/01_scripts/04_jellyfish
@@ -22,9 +22,10 @@ set -o nounset                              # Treat unset variables as an error
 #===============================================================================
 #       External variable 
 input=$1        #fastq.gz file read (HiFi on nano-hq)
-ploidy=$2       #to be passed as argument
-kmer_length=21  #to be passed as argument
-
+ploidy=$2       #an integer : either 1 or 2
+kmer_length=$3  #generally use the size of 21
+LENGTH=$4       #genome size in bp 
+datatype=$5     #hifi or ONT
 #===============================================================================
 source .cpu_mem
 
@@ -37,7 +38,7 @@ then
    #run jellyfish 
     jellyfish count -C -m 21 -s 1000000000 -t "$NCPUS_JELLY" <(zcat "$input") -o "$outdir"/reads.jf
 
-    if ! jellyfish histo -t 10 "$outdir"/reads.jf > "$outdir"/reads.histo ; then 
+    if ! jellyfish histo -t "$NCPUS_JELLY" "$outdir"/reads.jf > "$outdir"/reads.histo ; then 
 	    echo "jellyfish failed"
 	    exit 1
     fi
@@ -55,4 +56,20 @@ then
 else
     echo "genomescope2 output already exist"
 fi
+
+ #verify also the read error rate estimated from genomescope2:
+ err=$( tail -n1 "$outdir"/summary.txt |awk '{print $4/100}' ) 
+
+if [ $datatype == 'hifi' ] ;then threshold_err=0.01 ; else threshold_err=0.02 ; fi
+#check quality:
+ if awk -v d="$err" -v t="$threshold_err" 'BEGIN{exit !(d > t)}' ; 
+ then 
+     echo "=================================================================="
+     echo "!!!warning genome scope estimate of sequencing error is bad" ; 
+     echo "please verify genomeScope profiles and summary.txt !!!!" 
+     echo "=================================================================="
+     exit 
+ else 
+     echo " " ; 
+ fi
 
